In [25]:
import pandas as pd
import plotly.express as px

In [26]:
data0 = pd.read_csv(r'data\andijon\Annual SPEI Drought Index and.csv')
data2 = pd.read_csv(r'data\andijon\Average Largest 1-Day Precipitation-and.csv')
data3 = pd.read_csv(r'data\andijon\Average Largest 5-Day Cumulative Precipitation and.csv')
data4 = pd.read_csv(r'data\andijon\Precipitation amount during wettest days and.csv')
data5 = pd.read_csv(r'data\andijon\Relative Humidity and.csv')
data6 = pd.read_csv(r'data\andijon\Temperature-based Excess Mortality and.csv')
data7 = pd.read_csv(r'data\andijon\and-max-observed-timeseries-of-a (14).csv')
data8 = pd.read_csv(r'data\andijon\and-mean-observed-timeseries-of-a (14).csv')
data9 = pd.read_csv(r'data\andijon\and-min-observed-timeseries-of-a (14).csv')
data10 = pd.read_csv(r'data\andijon\and-precipitation-observed-timeseries-of-a (14).csv')

In [27]:
df1 = pd.concat([data10,data9,data8,data7], axis=1)
df1 = df1.loc[:, ~df1.columns.duplicated()]
df1

,Category,Precipitation (Annual Mean mm),5-year smooth (Gaussian Smooth),Average Minimum Surface Air Temperature (Annual Mean °C),Average Mean Surface Air Temperature (Annual Mean °C),Average Maximum Surface Air Temperature (Annual Mean °C)
0,1901,355.19,392.41,6.17,12.95,19.77
1,1902,461.47,363.31,7.10,13.87,20.68
2,1903,299.33,336.01,5.60,12.25,18.94
3,1904,283.19,312.24,5.85,12.85,19.88
4,1905,265.46,293.93,5.95,12.60,19.29
...,...,...,...,...,...,...
119,2020,283.19,295.98,7.61,14.31,21.02
120,2021,233.52,297.12,8.59,15.39,22.23
121,2022,368.99,300.49,9.67,15.68,21.72
122,2023,238.78,305.36,9.62,16.12,22.67
123,2024,354.42,311.00,8.93,15.28,21.68

In [28]:
df1 = df1.rename(columns={'Category':'Year'})

In [29]:
df1

,Year,Precipitation (Annual Mean mm),5-year smooth (Gaussian Smooth),Average Minimum Surface Air Temperature (Annual Mean °C),Average Mean Surface Air Temperature (Annual Mean °C),Average Maximum Surface Air Temperature (Annual Mean °C)
0,1901,355.19,392.41,6.17,12.95,19.77
1,1902,461.47,363.31,7.10,13.87,20.68
2,1903,299.33,336.01,5.60,12.25,18.94
3,1904,283.19,312.24,5.85,12.85,19.88
4,1905,265.46,293.93,5.95,12.60,19.29
...,...,...,...,...,...,...
119,2020,283.19,295.98,7.61,14.31,21.02
120,2021,233.52,297.12,8.59,15.39,22.23
121,2022,368.99,300.49,9.67,15.68,21.72
122,2023,238.78,305.36,9.62,16.12,22.67
123,2024,354.42,311.00,8.93,15.28,21.68

In [30]:
df2 = pd.concat([data0,data2,data3,data4,data5,data6], axis=1)
df2 = df2.loc[:, ~df2.columns.duplicated()]
df2

,Category,Annual SPEI Drought Index (spei index),Average Largest 1-Day Precipitation (mm),Average Largest 5-Day Cumulative Precipitation (mm),Precipitation amount during wettest days (mm),Relative Humidity (%),Temperature-based Excess Mortality (factor)
0,1950,NaN,24.25,36.10,9.87,51.86,0.05
1,1951,0.03,15.70,40.00,2.09,57.96,0.03
2,1952,0.12,18.25,41.52,5.53,53.27,0.04
3,1953,-0.11,16.71,37.02,5.49,56.51,0.04
4,1954,1.39,17.62,38.17,6.55,57.00,0.01
...,...,...,...,...,...,...,...
70,2020,-0.32,14.52,23.43,2.18,54.56,0.05
71,2021,-0.56,17.92,37.91,5.54,49.84,0.11
72,2022,-0.81,18.64,40.84,4.86,54.25,0.15
73,2023,-0.60,22.28,49.56,11.14,53.37,0.12
74,2024,-0.73,25.88,34.83,16.33,60.22,0.08

In [31]:
df2['Annual SPEI Drought Index (spei index)'] = df2['Annual SPEI Drought Index (spei index)'].fillna(df2['Annual SPEI Drought Index (spei index)'].mean())

In [32]:
df2.head()

,Category,Annual SPEI Drought Index (spei index),Average Largest 1-Day Precipitation (mm),Average Largest 5-Day Cumulative Precipitation (mm),Precipitation amount during wettest days (mm),Relative Humidity (%),Temperature-based Excess Mortality (factor)
0,1950,-0.010405,24.25,36.10,9.87,51.86,0.05
1,1951,0.030000,15.70,40.00,2.09,57.96,0.03
2,1952,0.120000,18.25,41.52,5.53,53.27,0.04
3,1953,-0.110000,16.71,37.02,5.49,56.51,0.04
4,1954,1.390000,17.62,38.17,6.55,57.00,0.01

In [33]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 6 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Year                                                      124 non-null    int64
 1   Precipitation (Annual Mean mm)                            124 non-null    float64
 2   5-year smooth (Gaussian Smooth)                           124 non-null    float64
 3   Average Minimum Surface Air Temperature (Annual Mean °C)  124 non-null    float64
 4   Average Mean Surface Air Temperature (Annual Mean °C)     124 non-null    float64
 5   Average Maximum Surface Air Temperature (Annual Mean °C)  124 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 5.9 KB

In [38]:
df2.isnull().sum()

Category                                               0
Annual SPEI Drought Index (spei index)                 0
Average Largest 1-Day Precipitation (mm)               0
Average Largest 5-Day Cumulative Precipitation (mm)    0
Precipitation amount during wettest days (mm)          0
Relative Humidity (%)                                  0
Temperature-based Excess Mortality (factor)            0
dtype: int64

In [39]:
import matplotlib.pyplot as plt

In [40]:
df1['Year']

0      1901
1      1902
2      1903
3      1904
4      1905
       ...
119    2020
120    2021
121    2022
122    2023
123    2024
Name: Year, Length: 124, dtype: int64

In [42]:
x = df1['Year']
y = df1['Precipitation (Annual Mean mm)']

In [54]:
line = px.line(df1, x='Year', y='Precipitation (Annual Mean mm)',)
line.show()
line.write_html('precipitation.html')

In [44]:
line = px.line(df1, x='Year', y='5-year smooth (Gaussian Smooth)')
line.show()

In [45]:
line = px.line(df1, x='Year',y='Average Minimum Surface Air Temperature (Annual Mean °C)')
line.show()

In [46]:
line = px.line(df1, x='Year',y='Average Mean Surface Air Temperature (Annual Mean °C)')
line.show()

In [47]:
line = px.line(df1, x='Year',y='Average Maximum Surface Air Temperature (Annual Mean °C)')
line.show()

In [48]:
line = px.line(df2, x='Category',y='Annual SPEI Drought Index (spei index)')
line.show()

In [49]:
line = px.line(df2, x='Category',y='Average Largest 1-Day Precipitation (mm)')
line.show()

In [50]:
line = px.line(df2, x='Category',y='Average Largest 5-Day Cumulative Precipitation (mm)')
line.show()

In [51]:
line = px.line(df2, x='Category',y='Precipitation amount during wettest days (mm)')
line.show()

In [52]:
line = px.line(df2, x='Category',y='Relative Humidity (%)')
line.show()

In [53]:
line = px.line(df2, x='Category',y='Temperature-based Excess Mortality (factor)')
line.show()